= grinaddr.sh

A script to automate creating and using temporal payment addresses through https://grinaddr.io service

== How to use

NOTE: The script expects that you have `grin` command in your PATH, if you don't it configured, please edit the script
and put the right path to the grin binary

The script automates the whole process of requesting Grin coins, by creating a new URL for payments, listening for
incoming slate, calling _grin wallet_ to add outputs and send it back to sender.

.To do whole operation just call it as:
----
./grinaddr.sh
----

The output it will give you will be an URL you can pass to another party.

.Demo
----
./grinaddr.sh

Running grinaddr.sh version 0.2.0 with grin version grin 1.0.0

Receiving GRIN coins through https://grinaddr.io randezvous

TRANSFER ID O9JyggmYZ4AcZYpbfz3bCPYmuw6FzNpavfhgpTvoomTpiGQpb

Give following URL to sender to send coins to you:
https://send.grinaddr.io/O9JyggmYZ4AcZYpbfz3bCPYmuw6FzNpavfhgpTvoomTpiGQpb

Press ENTER after you'll give URL to sender
Waiting for a slate to receive coins...

Received slate to accept coins, stored as grinaddr-20190128120709-slate.json
Please sing using Grin wallet:
Password:
Command 'receive' completed successfully
{"status":true,"message":"Slate was received, will be transmitted to transfer sender"}
Slate sent back to sender for finalization
Please verify transaction on blockchain, it make take time while sender will broadcast it to the network
----

In that demo the script:

1. Created a payment URL as https://send.grinaddr.io/O9JyggmYZ4AcZYpbfz3bCPYmuw6FzNpavfhgpTvoomTpiGQpb
2. Listen for a payment sent to it.
3. Right after another party send coins to the address the script calls your _grin wallet_ to sign outputs (it asks for
a password)
4. Send it back to sender for publishing a transaction to blockchain
5. PROFIT!

For a sender it doesn't require any changes, it's an opaque process and should be compatible with most of the software.

== How it works

The service creates a uniq URL and expects that both parties will connect to it at about the same time. Service allows
to exchange slate (payment document) between parties.

The link can be active for up to 24 hours, and connection time to live is up to 1 hour. If connection was dropped, you can continue
by connecting to the same URL by calling `grinaddr.sh continue <ID>`


